/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.ttymonkey.search

import kotlinx.serialization.ExperimentalSerializationApi

@ExperimentalSerializationApi
fun main(args: Array<String>) {
    App(args).run()
}

